import type { Metadata } from 'next';
import { Inter, Roboto_Mono, Inter_Tight } from 'next/font/google';
import { I18nProvider } from './i18n-provider';
import SmoothScrollWrapper from './smooth-scroll-wrapper';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  weight: ['500'], // Medium
  variable: '--font-inter',
});

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  weight: ['400'], // Regular
  variable: '--font-roboto-mono',
});

const interTight = Inter_Tight({
  subsets: ['latin'],
  weight: ['500', '700'], // Medium, Bold
  variable: '--font-inter-tight',
});

export const metadata: Metadata = {
  title: 'CTRL Studio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="/cube-bg.svg" as="image" type="image/svg+xml" />
        <link rel="preload" href="/cube.png" as="image" />
        <link rel="preload" href="/why-1.webp" as="image" />
        <link rel="preload" href="/why-2.webp" as="image" />
        <link rel="preload" href="/why-3.webp" as="image" />
        <link rel="preload" href="/bg-video.webp" as="script" />
      </head>
      <body className={` ${inter.variable} ${robotoMono.variable} ${interTight.variable} antialiased`}>
        <I18nProvider>
          <SmoothScrollWrapper>{children}</SmoothScrollWrapper>
        </I18nProvider>
        <div id="modal-root" />
      </body>
    </html>
  );
}
